### ISSUE TITLE
'Booking' object has no attribute 'find_element_by_css_selector'

### ISSUE THREAD

**Issue by hailong18102002** [gilbertekalea/booking.com_crawler#4]
Hi,
I am using window for this project
Then I run python runbot.py
But getting this error:
Traceback (most recent call last):
  File "d:\visual code\danang aihub\booking.com_crawler\runbot.py", line 35, in <module>
    bot.change_currency(currency="USD")
  File "d:\visual code\danang aihub\booking.com_crawler\booking\booking.py", line 79, in change_currency
    currency_element = self.find_element_by_css_selector(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Booking' object has no attribute 'find_element_by_css_selector'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\visual code\danang aihub\booking.com_crawler\runbot.py", line 13, in <module>
    with Booking() as bot:
TypeError: Booking.__exit__() takes 1 positional argument but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\visual code\danang aihub\booking.com_crawler\runbot.py", line 55, in <module>
    raise SyntaxError
SyntaxError: None

Am I wrong somewhere, please help.

**Comment by elio1fiore** [comment]
I have this problem too +1
